### ISSUE TITLE
zpy-zumo fails to properly install on Windows with Conda

### ISSUE THREAD

**Issue by swpecht** [ZumoLabs/zpy#105]
**Describe the bug**
zpy fails to properly install -- any invocation gives an error -- on Windows using `pip install zpy-zumo` in Anaconda

Likely cause: https://github.com/Toblerity/Shapely/issues/1032

**To Reproduce**
* Be on Windows
* Create a new python env in Anaconda
* Install zpy-zumo `pip install zpy-zumo` in the Anaconda cli
* Run `zpy`

```
(zpy-test) C:\Users\steve>zpy
Traceback (most recent call last):
  File "d:\anaconda3\envs\zpy-test\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\anaconda3\envs\zpy-test\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\zpy-test\Scripts\zpy.exe\__main__.py", line 4, in <module>
  File "d:\anaconda3\envs\zpy-test\lib\site-packages\cli\cli.py", line 2, in <module>
    from cli.utils import parse_args, resolve_sweep
  File "d:\anaconda3\envs\zpy-test\lib\site-packages\cli\utils.py", line 1, in <module>
    from cli.config import read_config
  File "d:\anaconda3\envs\zpy-test\lib\site-packages\cli\config.py", line 1, in <module>
    from zpy.files import to_pathlib_path
  File "d:\anaconda3\envs\zpy-test\lib\site-packages\zpy\__init__.py", line 18, in <module>
    from zpy import image
  File "d:\anaconda3\envs\zpy-test\lib\site-packages\zpy\image.py", line 12, in <module>
    from shapely.geometry import MultiPolygon, Polygon
  File "d:\anaconda3\envs\zpy-test\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "d:\anaconda3\envs\zpy-test\lib\site-packages\shapely\geometry\base.py", line 19, in <module>
    from shapely.coords import CoordinateSequence
  File "d:\anaconda3\envs\zpy-test\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "d:\anaconda3\envs\zpy-test\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "d:\anaconda3\envs\zpy-test\lib\ctypes\__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'd:\anaconda3\envs\zpy-test\Library\bin\geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Expected behavior**
zpy doesn't give an error when invoked.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: zpy 1.1.3

**Additional context**
Seems to be related to this issue with shapely: https://github.com/Toblerity/Shapely/issues/1032
Running `conda install shapely` after install fixes the issue.

Fix proposed for Shapely 1.8

**Comment by HugoCMU** [comment]
shapely fix has been pushed it seems?
