### ISSUE TITLE
AttributeError: 'Object' object has no attribute 'seg'

### ISSUE THREAD

**Issue by ssssss-ai** [ZumoLabs/zpy#154]
**MY CODE**
import bpy
import zpy

saver = zpy.saver_image.ImageSaver(description="Suzannes from a camera view")
suzanne_seg_color = zpy.color.random_color(output_style="frgb")
saver.add_category(name="Suzanne", color=suzanne_seg_color)
zpy.objects.segment("Suzanne", color=suzanne_seg_color)

**ERROR**

Traceback (most recent call last):
  File "E:\blender-train\zpy1.blend\Text", line 14, in <module>
  File "E:\blr\2.93\python\lib\site-packages\zpy\objects.py", line 297, in segment
    obj.seg.instance_name = name
AttributeError: 'Object' object has no attribute 'seg'
Error: Python script failed, check the message in the system console

**Comment by ssssss-ai** [comment]
I have  solved it.For some reason, the "ZPY" folder and the "ZPY ADDON" folder are put together.I have separated them.
