### ISSUE TITLE
Error to install addon

### ISSUE THREAD

**Issue by sjimenez44** [ZumoLabs/zpy#26]
I'm trying to install the addon v0.9.9, but I get the below error, I am stuck and I don't know how to fix it.

Traceback (most recent call last):
  File "/app/blender/2.92/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "~/.var/app/org.blender.Blender/config/blender/2.92/scripts/addons/zpy_addon/__init__.py", line 58, in <module>
    from . import export_panel
  File "~/.var/app/org.blender.Blender/config/blender/2.92/scripts/addons/zpy_addon/export_panel.py", line 10, in <module>
    import zpy
ModuleNotFoundError: No module named 'zpy'

 - OS: Ubuntu 18.04
 - Blender: 2.92

**Comment by kursad-zumolabs** [comment]
You need to use the developer mode installation method on Windows. Please see the documentation here.

https://github.com/ZumoLabs/zpy/blob/main/docs/developer_mode.md#install-windows-developer-environment-

**Comment by lchunleo** [comment]
can share how to do in windows developer environment? the link seem unavailable

**Comment by hu-po** [comment]
Haven't tested the installation instructions for windows in a long time, so support is limited, but maybe this can help: https://github.com/ZumoLabs/zpy/blob/main/docs/addon/install.md
