### ISSUE TITLE
AttributeError: Calling operator "bpy.ops.cycles.add_aov" error, could not be found

### ISSUE THREAD

**Issue by VictorAtPL** [ZumoLabs/zpy#27]
**Describe the bug**
I downloaded Suzanne 1 example from your repository and run it using Blender 2.92 and your library.

I got following error:

```
Read blend: untitled.blend
 Setting render engine to CYCLES to use AOV
 Setting render engine to CYCLES to use AOV
Traceback (most recent call last):
  File "untitled.blend/run.py", line 78, in <module>
  File "untitled.blend/run.py", line 35, in run
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/zpy/render.py", line 204, in render_aov
    output_node = make_aov_file_output_node(style=style)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/zpy/render.py", line 82, in make_aov_file_output_node
    zpy.render.make_aov_pass(style)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/zpy/render.py", line 41, in make_aov_pass
    bpy.ops.cycles.add_aov()
  File "/home/piotr/Files/blender/blender-2.92.0-linux64/2.92/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.cycles.add_aov" error, could not be found
  In call to configurable 'make_aov_pass' (<function make_aov_pass at 0x7f8f0f9aaf80>)
  In call to configurable 'make_aov_file_output_node' (<function make_aov_file_output_node at 0x7f8f0f9af050>)
  In call to configurable 'render_aov' (<function render_aov at 0x7f8f0f9b5050>)
Error: Python script failed, check the message in the system console
```

**To Reproduce**
1. Install Blender 2.92.
2. Install zpy addon and zpy-zumo Python library.
3. Download Suzanne 1 run.py script.
4. Run Suzanne 1 run.py script.

**Additional context**

> This seems related to Blender 2.92, we are still on 2.91. We will let you know when this is ready to go. If you can make a ticket for this it will help us out :)
>
>
>Hugo Ponte
>Co-Founder & CTO

**Comment by HugoCMU** [comment]
It seems like that call no longer exists in 2.92. We have added a compatibility check: https://github.com/ZumoLabs/zpy/commit/3f4581b45b338ffbcc53f09d3d5ead2b81ff49f8
