### ISSUE TITLE
KeyError: 'bpy_struct[key]: key "aovs" not found'

### ISSUE THREAD

**Issue by VictorAtPL** [ZumoLabs/zpy#28]
**Describe the bug**
I downloaded Suzanne 1 example from your repository and run it using Blender 2.91 and your library.

I got following error:

```
Traceback (most recent call last):
  File "/run.py", line 78, in <module>
  File "/run.py", line 35, in run
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/zpy/render.py", line 204, in render_aov
    output_node = make_aov_file_output_node(style=style)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/zpy/render.py", line 82, in make_aov_file_output_node
    zpy.render.make_aov_pass(style)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/zpy/render.py", line 42, in make_aov_pass
    view_layer['aovs'][-1]['name'] = style
KeyError: 'bpy_struct[key]: key "aovs" not found'
  In call to configurable 'make_aov_pass' (<function make_aov_pass at 0x7f73bfd25f80>)
  In call to configurable 'make_aov_file_output_node' (<function make_aov_file_output_node at 0x7f73bfd25ef0>)
  In call to configurable 'render_aov' (<function render_aov at 0x7f73bfd28f80>)
Error: Python script failed, check the message in the system console
```

**To Reproduce**
1. Install Blender 2.91.
2. Install zpy addon and zpy-zumo Python library.
3. Download Suzanne 1 run.py script.
4. Run Suzanne 1 run.py script.

**Expected behavior**
Suzanne 1 run.py script run without errors.

**Comment by VictorAtPL** [comment]
After changing 44th line of `render.py` to `view_layer.cycles.aovs[-1]['name'] = style` it works.
However when I run Suzanne 1, then I get new error:
```
Saved: /tmp/output/IMG_00000004_rgb.png0001
imb_savepng: Cannot open file for writing: '/tmp/'
/tmp/: Is a directory
 Time: 00:05.06 (Saving: 00:00.01)

Error: Render error (Is a directory) cannot save: '/tmp/'
Render raised exception Error: Render error (Is a directory) cannot save: '/tmp/'

Saved: /tmp/output/IMG_00000004_iseg.png0001
imb_savepng: Cannot open file for writing: '/tmp/'
/tmp/: Is a directory
 Time: 00:00.05 (Saving: 00:00.00)

Error: Render error (Is a directory) cannot save: '/tmp/'
Render raised exception Error: Render error (Is a directory) cannot save: '/tmp/'

Could not find path at /tmp/output/.zumometa
Error when visualizing No module named 'seaborn'
Traceback (most recent call last):
  File "/run.py", line 91, in <module>
  File "/run.py", line 85, in run
    
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/zpy/output_coco.py", line 317, in output_annotations
    annotation_file=annotation_path, data_dir=self.saver.output_dir)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/piotr/Files/blender/bar/lib/python3.7/site-packages/zpy/output_coco.py", line 363, in parse_coco_annotations
    f'no annotations found in {annotation_file}')
zpy.output_coco.COCOParseError: no annotations found in /tmp/output/coco_annotations.json
  In call to configurable 'parse_coco_annotations' (<function parse_coco_annotations at 0x7f73bfd42f80>)
  In call to configurable 'output_annotations' (<function OutputCOCO.output_annotations at 0x7f73bfd4e950>)
Error: Python script failed, check the message in the system console
```

`/tmp/output/coco_annotations.json` exists. Also I don't get what these errors regarding storing files in /tmp means. Files were created:
![image](https://user-images.githubusercontent.com/1886347/111205927-0e9c2680-85c8-11eb-9342-b817c973af89.png)

**Comment by HugoCMU** [comment]
Thanks for making this ticket! Answers below:
- Fixed the `KeyError: 'bpy_struct[key]: key "aovs" not found'` with https://github.com/ZumoLabs/zpy/commit/7d2cc2aaf9fe4bb8393344803cb23e407fb55e35.
- This error `zpy.output_coco.COCOParseError: no annotations found in /tmp/output/coco_annotations.json` happens when there aren't annotations likely due to none of the objects being segmented. Have you tried adding a material to the Suzanne object?
- I have made a new issue to remove the render errors associated with `/tmp` . These are Blender errors that don't seem to affect the actual script and happen every time: https://github.com/ZumoLabs/zpy/issues/29

**Comment by VictorAtPL** [comment]
Hello @HugoCMU,

firstly - thank you for rapid response. I really appreciate.

1. Thank you for fixing the error. I pulled new commits from master and installed zpy-zumo once again. Now the problem doesn't appear.
2. Error disappeared after setting the material. My fault. I should have watch whole YouTube video and then I would now that.
3. Ok, so I will simply ignore these errors, but they are currently misleading. It's good you've opened a new PR.

I am closing issue. Now I will try running other Suzanne demos and after that to integrate your library with my code. Thank you!

FYI, my current log is as follows:
```
Read prefs: /home/piotr/.config/blender/2.91/config/userpref.blend
/run/user/1000/gvfs/ non-existent directory
found bundled python: /home/piotr/Files/blender/bar
Reloading zpy_addon files.
Info: Deleted 1 object(s)

 Setting render engine to CYCLES to use AOV
 Setting render engine to CYCLES to use AOV
Saved: /tmp/output/IMG_00000000_rgb.png0001
imb_savepng: Cannot open file for writing: '/tmp/'
/tmp/: Is a directory
 Time: 00:04.88 (Saving: 00:00.01)

Error: Render error (Is a directory) cannot save: '/tmp/'
Render raised exception Error: Render error (Is a directory) cannot save: '/tmp/'

Saved: /tmp/output/IMG_00000000_iseg.png0001
imb_savepng: Cannot open file for writing: '/tmp/'
/tmp/: Is a directory
 Time: 00:00.05 (Saving: 00:00.00)

Error: Render error (Is a directory) cannot save: '/tmp/'
Render raised exception Error: Render error (Is a directory) cannot save: '/tmp/'

Saved: /tmp/output/IMG_00000001_rgb.png0001
imb_savepng: Cannot open file for writing: '/tmp/'
/tmp/: Is a directory
 Time: 00:03.57 (Saving: 00:00.01)

Error: Render error (Is a directory) cannot save: '/tmp/'
Render raised exception Error: Render error (Is a directory) cannot save: '/tmp/'

Saved: /tmp/output/IMG_00000001_iseg.png0001
imb_savepng: Cannot open file for writing: '/tmp/'
/tmp/: Is a directory
 Time: 00:00.05 (Saving: 00:00.00)

Error: Render error (Is a directory) cannot save: '/tmp/'
Render raised exception Error: Render error (Is a directory) cannot save: '/tmp/'

Saved: /tmp/output/IMG_00000002_rgb.png0001
imb_savepng: Cannot open file for writing: '/tmp/'
/tmp/: Is a directory
 Time: 00:04.96 (Saving: 00:00.03)

Error: Render error (Is a directory) cannot save: '/tmp/'
Render raised exception Error: Render error (Is a directory) cannot save: '/tmp/'

Saved: /tmp/output/IMG_00000002_iseg.png0001
imb_savepng: Cannot open file for writing: '/tmp/'
/tmp/: Is a directory
 Time: 00:00.06 (Saving: 00:00.00)

Error: Render error (Is a directory) cannot save: '/tmp/'
Render raised exception Error: Render error (Is a directory) cannot save: '/tmp/'

Saved: /tmp/output/IMG_00000003_rgb.png0001
imb_savepng: Cannot open file for writing: '/tmp/'
/tmp/: Is a directory
 Time: 00:03.93 (Saving: 00:00.01)

Error: Render error (Is a directory) cannot save: '/tmp/'
Render raised exception Error: Render error (Is a directory) cannot save: '/tmp/'

Saved: /tmp/output/IMG_00000003_iseg.png0001
imb_savepng: Cannot open file for writing: '/tmp/'
/tmp/: Is a directory
 Time: 00:00.04 (Saving: 00:00.00)

Error: Render error (Is a directory) cannot save: '/tmp/'
Render raised exception Error: Render error (Is a directory) cannot save: '/tmp/'

Saved: /tmp/output/IMG_00000004_rgb.png0001
imb_savepng: Cannot open file for writing: '/tmp/'
/tmp/: Is a directory
 Time: 00:05.25 (Saving: 00:00.01)

Error: Render error (Is a directory) cannot save: '/tmp/'
Render raised exception Error: Render error (Is a directory) cannot save: '/tmp/'

Saved: /tmp/output/IMG_00000004_iseg.png0001
imb_savepng: Cannot open file for writing: '/tmp/'
/tmp/: Is a directory
 Time: 00:00.06 (Saving: 00:00.00)

Error: Render error (Is a directory) cannot save: '/tmp/'
Render raised exception Error: Render error (Is a directory) cannot save: '/tmp/'

Could not find path at /tmp/output/.zumometa
Could not find path at /tmp/output/ZUMO_META.json
Could not find path at /tmp/output/coco_annotations.json
```
