### ISSUE TITLE
 'Object' object has no attribute 'seg'

### ISSUE THREAD

**Issue by RinuMic** [ZumoLabs/zpy#56]
system details:
OS: Windows 10
Blender version : 2.92 (tried on 2.91.0 with same error)

I'm getting the following error when I tried to execute run.py for Suzanne: Part 1. How should I solve this?

Traceback (most recent call last):
  File "\run.py", line 78, in <module>
  File "\run.py", line 21, in run
  File "D:\files\blender\2.92\python\lib\zpy\objects.py", line 244, in segment
    obj.seg.instance_name = name
AttributeError: 'Object' object has no attribute 'seg'
Error: Python script failed, check the message in the system console

**Comment by kursad-zumolabs** [comment]
You need to have the zpy add-on installed properly. Zpy consists of the zpy module and the zpy Blender add-on.

**Comment by HugoCMU** [comment]
One way to verify that the zpy add-on is properly installed is to check that the zpy panel exists:
![image](https://user-images.githubusercontent.com/8493427/114730560-d5092900-9cf5-11eb-8b62-d9f83c146ec9.png)
